---

- hosts: all
  become: true
  tasks:

    - name: update repository index, install apache2 and php packages for Ubuntu
      package:
        name: 
          - apache2
          - libapache2-mod-php 
        state: latest
        update_cache: yes  
  
