---

- hosts: all
  become: true
  tasks:
    - name: install updates (Debian)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"

    - name: install updates (Ubuntu)
      tags: apache,apache2
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy: 
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644  

- hosts: ubuntuserver
  become: true
  tasks:
    - name: update repository index, install apache2 and php packages for Ubuntu
      package:
        name: 
          - apache2
          - libapache2-mod-php 
        state: latest
      when: ansible_distribution == "Ubuntu"
  
